### PR TITLE
Fix Compile Error

### PR DESCRIPTION
**Pull request by TingyiChen**
These files is already defined in device/cyanogen/msm8916-common/rootdir/Android.mk.They are obsolete.

### CODE REVIEW

**Comment by dev-harsh1998** [comment]
Ok solve them when build compeletes inform me

**Comment by TingyiChen** [comment]
@dev-harsh1998 
s

**Comment by TingyiChen** [comment]
@dev-harsh1998 How to solve it?plz give me help

**Comment by TingyiChen** [comment]
@dev-harsh1998 i know how to solve it.try to edit vendor/lenovo/msm8916/Android.mk

**Comment by dev-harsh1998** [comment]
After 3 hours I am Doinf Homework till then try yourself

**Comment by TingyiChen** [comment]
i have to go to do my homework,too....i have chinese and math needed to be finished...

**Comment by TingyiChen** [comment]
see you this night

**Comment by dev-harsh1998** [comment]
Clone Vendor Its Error By vendor

**Comment by TingyiChen** [comment]
@dev-harsh1998 yes.i have solved it

**Comment by TingyiChen** [comment]
edit vendor/lenovo/msm8916/Android.mk and change the product name to wt86518

**Comment by dev-harsh1998** [comment]
@TingyiChen  Sync The latest vendor i have added Support for volte

**Comment by TingyiChen** [comment]
ok.i synced

**Comment by dev-harsh1998** [comment]
@TingyiChen How about Compilation ?

**Comment by TingyiChen** [comment]
Finished,but I am still on bed now.

**Comment by TingyiChen** [comment]
I am going to get up now

**Comment by TingyiChen** [comment]
Can't boot

**Comment by TingyiChen** [comment]
It rebooted

**Comment by TingyiChen** [comment]
Compile Successfully but can't boot.It rebooted @dev-harsh1998

**Comment by TingyiChen** [comment]
i modified device/cyanogen/msm8916-common,now it's compiling

**Pull request closed without merging**
