### PR TITLE
Update partition info for 8g rom

### PR DESCRIPTION
**Pull request by TingyiChen**

### CODE REVIEW

**Comment by dev-harsh1998** [comment]
@TingyiChen i will make a unified device tree first check wether this tree compiles and boot ?

**Comment by TingyiChen** [comment]
i will start compile soon

**Comment by TingyiChen** [comment]
now i am cloneing the tree

**Comment by TingyiChen** [comment]
if i use the binary files in k31-t3,will it work?

**Comment by TingyiChen** [comment]
can't load device tree normally

**Comment by dev-harsh1998** [comment]
? There may be some errors if its hard send ss

**Comment by TingyiChen** [comment]
i created a pr.please merge it

**Comment by dev-harsh1998** [comment]
Is this tree compiling ?

**Comment by TingyiChen** [comment]
i am compiling

**Comment by TingyiChen** [comment]
maybe in several hours i will reply you

**Comment by dev-harsh1998** [comment]
Ok If it Compiles i will make Unified Device Tree for Both Devices K3s And K30-T

**Comment by TingyiChen** [comment]
an error occured...

**Comment by dev-harsh1998** [comment]
Send screenshot

**Comment by TingyiChen** [comment]
I solved them and created a pr

**Comment by TingyiChen** [comment]
@dev-harsh1998

**Comment by TingyiChen** [comment]
now i am mkaing otapackage

**Pull request closed without merging**
